In [2]:
import requests
import json
import os
import sqlalchemy
import pandas as pd
import mdapi_functions as md
from IPython.display import display, Markdown
import markdown
from bokeh.plotting import figure, show
from bokeh.models import (Span, TabPanel, Tabs, ColumnDataSource, DataCube,
                          GroupingInfo, StringFormatter, SumAggregator,
                          TableColumn, HoverTool, LinearColorMapper, ColorBar)
from bokeh.palettes import Category20c, Cividis256
from bokeh.transform import cumsum
from bokeh.io import output_notebook
from math import pi
from datetime import datetime
import datacite_api_functions as dcf
import numpy as np
import data_doc_helper as dh

from math import pi
import math
import time

import data_doc_helper as dh
import geopandas as gpd


from bokeh.io import output_notebook
output_notebook(hide_banner=True)

import nbformat as nbf
from nbconvert.preprocessors import ExecutePreprocessor
import tqdm 
 
API_KEY = os.environ['FASTAPI_KEY']

api_url = "https://mms-production-3b476d9d2c44.herokuapp.com/meta/api/"

In [2]:
output_notebook(hide_banner=True)

x = {
    'United States': 157,
    'United Kingdom': 93,
    'Japan': 89,
    'China': 63,
    'Germany': 44,
    'India': 42,
    'Italy': 40,
    'Australia': 35,
    'Brazil': 32,
    'France': 31,
    'Taiwan': 31,
    'Spain': 29,
}

data = pd.Series(x).reset_index(name='value').rename(columns={'index': 'country'})
data['angle'] = data['value']/data['value'].sum() * 2*pi
data['color'] = Category20c[len(x)]

p = figure(height=350, title="Pie Chart", toolbar_location=None,
           tools="hover", tooltips="@country: @value", x_range=(-0.5, 1.0))

p.wedge(x=0, y=1, radius=0.4,
        start_angle=cumsum('angle', include_zero=True), end_angle=cumsum('angle'),
        line_color="white", fill_color='color', legend_field='country', source=data)

p.axis.axis_label = None
p.axis.visible = False
p.grid.grid_line_color = None

show(p)

In [ ]:
from bokeh.plotting import figure, show, output_file

p = figure(x_range=(-1400000, 400000), y_range=(6300000, 8800000),
           x_axis_type="mercator", y_axis_type="mercator")
p.add_tile("OpenStreetMap Mapnik")


def latlon_to_mercator(lat, lon):
    r_major = 6378137.000
    x = r_major * math.radians(lon)
    scale = x / lon
    y = 180.0 / math.pi * math.log(math.tan(math.pi / 4.0 + lat * (math.pi / 180.0) / 2.0)) * scale
    return (x, y)

# --- 2. Define Northern Ireland Polygon (Rough Lat/Lon) ---
# A simplified shape roughly tracing the border of NI
ni_lats = [55.3, 55.2, 54.8, 54.6, 54.1, 54.1, 54.2, 54.5, 54.8] 
ni_lons = [-6.8, -6.2, -5.8, -5.5, -6.0, -7.3, -7.8, -8.1, -7.5]

# Convert these lists to Mercator
mercator_x = []
mercator_y = []
for lat, lon in zip(ni_lats, ni_lons):
    x, y = latlon_to_mercator(lat, lon)
    mercator_x.append(x)
    mercator_y.append(y)

source = ColumnDataSource(data=dict(
    xs=[mercator_x], 
    ys=[mercator_y],
    name=["Northern Ireland"]
))

p.patches('xs', 'ys', source=source,
          fill_color="green", fill_alpha=0.2, 
          line_color="darkgreen", line_width=2)


p.grid.visible = False

show(p)

In [ ]:
geo_polys = gpd.read_file("regions.geojson")

In [ ]:
geo_counts = pd.read_csv("geo_locations.csv").drop(columns=["index", "source_stem"]).set_index("source").transpose().reset_index()
geo_counts

In [ ]:
# l = id, r = source
geo_data = geo_polys.merge(geo_counts, left_on="id", right_on="index")

In [ ]:
geo_data2 = geo_data.to_crs(epsg=3857)

In [ ]:
geo_data2

In [ ]:
def get_bokeh_coords(geometry):
    """
    Extracts x and y coordinates from a shapely Geometry.
    Returns a tuple (x_coords, y_coords).
    """
    if geometry.geom_type == 'Polygon':
        x, y = geometry.exterior.xy
        return [[list(x)], [list(y)]]
    elif geometry.geom_type == 'MultiPolygon':
        xs = []
        ys = []
        for poly in geometry.geoms:
            x, y = poly.exterior.xy
            xs.append(list(x))
            ys.append(list(y))
        return [xs, ys]
    return [[], []]

In [ ]:
geo_data2['bokeh_coords'] = geo_data2['geometry'].apply(get_bokeh_coords)
geo_data2['xs'] = geo_data2['bokeh_coords'].apply(lambda x: x[0])
geo_data2['ys'] = geo_data2['bokeh_coords'].apply(lambda x: x[1])

In [ ]:
source = ColumnDataSource(geo_data2.drop(columns=["geometry", "bokeh_coords"]))

In [ ]:
# --- 3. Set up the Color Mapper ---
# 'low' and 'high' define the range of your data
color_mapper = LinearColorMapper(palette=Viridis256, low=0, high=100)

In [ ]:
p = figure(title="UK Choropleth Map", 
           tools="pan,wheel_zoom,reset,save",
           x_axis_location=None, y_axis_location=None,
           x_axis_type="mercator", y_axis_type="mercator") # Hide axes for a clean look
p.grid.grid_line_color = None

In [ ]:
p.patches('xs', 'ys', source=source,
         # fill_color={'field': 'TEDS', 'transform': color_mapper}, # The magic line
          fill_alpha=0.8,
          line_color="white", 
          line_width=0.5)

In [ ]:
# --- 5. Add UI Elements (Hover & ColorBar) ---
# Add a hover tool to see the region name and count
hover = HoverTool(tooltips=[
    ("Region", "@id"),
    ("Count", "@TEDS")
])
p.add_tools(hover)

# Add a color bar legend
# color_bar = ColorBar(color_mapper=color_mapper, label_standoff=12, border_line_color=None, location=(0,0))
# p.add_layout(color_bar, 'right')

In [ ]:
show(p)

In [ ]:
geo_data['bokeh_coords'] = geo_data['geometry'].apply(get_bokeh_coords)
geo_data['xs'] = geo_data['bokeh_coords'].apply(lambda x: x[0])
geo_data['ys'] = geo_data['bokeh_coords'].apply(lambda x: x[1])

source = ColumnDataSource(geo_data.drop(columns=["geometry", "bokeh_coords"]))

# --- 3. Set up the Color Mapper ---
# 'low' and 'high' define the range of your data
color_mapper = LinearColorMapper(palette=Viridis256, low=0, high=100)

p = figure(title="UK Choropleth Map", 
           tools="pan,wheel_zoom,reset,save",
           x_axis_location=None, y_axis_location=None) # Hide axes for a clean look
p.grid.grid_line_color = None

p.patches('xs', 'ys', source=source,
         # fill_color={'field': 'TEDS', 'transform': color_mapper}, # The magic line
          fill_alpha=0.8,
          line_color="black", 
          line_width=0.5)

# --- 5. Add UI Elements (Hover & ColorBar) ---
# Add a hover tool to see the region name and count
hover = HoverTool(tooltips=[
    ("Region", "@id"),
    ("Count", "@TEDS")
])
p.add_tools(hover)

# Add a color bar legend
# color_bar = ColorBar(color_mapper=color_mapper, label_standoff=12, border_line_color=None, location=(0,0))
# p.add_layout(color_bar, 'right')

show(p)

In [ ]:
import pandas as pd
import geopandas as gpd
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, LinearColorMapper, HoverTool
from bokeh.palettes import Viridis256

# --- 1. Explode MultiPolygons into Polygons ---
# This ensures that a region with islands becomes multiple rows, 
# making it much easier for Bokeh to render.
geo_data = geo_data.explode(index_parts=True).reset_index(drop=True)

# --- 2. Simplified Coordinate Extraction ---
def get_coords(geometry):
    """Extract simple x and y lists from a single Polygon."""
    if geometry.geom_type == 'Polygon':
        x, y = geometry.exterior.xy
        return list(x), list(y)
    return [], []

# Apply the simplified extraction
coords = geo_data['geometry'].apply(get_coords)
geo_data['xs'] = coords.apply(lambda x: x[0])
geo_data['ys'] = coords.apply(lambda x: x[1])

# --- 3. Clean and Prepare Source ---
# Ensure we drop the geometry object to avoid serialization errors
df_final = pd.DataFrame(geo_data.drop(columns=["geometry"]))
source = ColumnDataSource(df_final)

# --- 4. Setup the Plot ---
color_mapper = LinearColorMapper(palette=Viridis256, low=0, high=100)

# We use DataRange1d (default) but ensure the figure is sized correctly
p = figure(title="UK Choropleth Map", 
           tools="pan,wheel_zoom,reset,save",
           x_axis_location=None, y_axis_location=None,
           match_aspect=True) # match_aspect prevents the UK from looking 'stretched'

p.patches('xs', 'ys', source=source,
          fill_color={'field': 'TEDS', 'transform': color_mapper}, 
          fill_alpha=0.8,
          line_color="black", 
          line_width=0.5)

# Add HoverTool
hover = HoverTool(tooltips=[
    ("Region", "@id"),
    ("Count", "@TEDS")
])
p.add_tools(hover)

p.grid.grid_line_color = None
show(p)

In [ ]:
# Explodes multi-polygons into polygons
geo_data2 = geo_data2.explode(index_parts=True).reset_index(drop=True)

# Extracts coordinates
def get_coords(geometry):
    """Extract simple x and y lists from a single Polygon."""
    if geometry.geom_type == 'Polygon':
        x, y = geometry.exterior.xy
        return list(x), list(y)
    return [], []

coords = geo_data2['geometry'].apply(get_coords)
geo_data2['xs'] = coords.apply(lambda x: x[0])
geo_data2['ys'] = coords.apply(lambda x: x[1])

# drop geometry
df_final = pd.DataFrame(geo_data2.drop(columns=["geometry"]))
source = ColumnDataSource(df_final)

# --- 4. Setup the Plot ---
color_mapper = LinearColorMapper(palette=Viridis256, 
                                 low=df_final["TEDS"].min(), 
                                 high=df_final["TEDS"].max())

# We use DataRange1d (default) but ensure the figure is sized correctly
p = figure(title="UK Choropleth Map", 
           tools="pan,wheel_zoom,reset,save",
           x_axis_location=None, y_axis_location=None,
           x_axis_type="mercator", y_axis_type="mercator",
           match_aspect=True) # match_aspect prevents the UK from looking 'stretched'

p.patches('xs', 'ys', source=source,
          fill_color={'field': 'TEDS', 'transform': color_mapper}, 
          fill_alpha=0.8,
          line_color="black", 
          line_width=0.5)

# Add HoverTool
hover = HoverTool(tooltips=[
    ("Region", "@id"),
    ("Count", "@TEDS")
])
p.add_tools(hover)

# Add a color bar legend
color_bar = ColorBar(color_mapper=color_mapper, label_standoff=12, border_line_color=None, location=(0,0))
p.add_layout(color_bar, 'right')

p.grid.grid_line_color = None
show(p)

In [ ]:
def study_choropleth(study: str):
    """Generates choropleth map showing regional coverage of participants. 

    Args:
        study (str): study (e.g. "TEDS")

    Returns:
        Markdown/Bokeh: Either "unavailable" or Bokeh plot of choropleth 
    """

    # read counts (from CSV for now, TODO: API endpoint), transform
    #geo_counts = pd.read_csv("geo_locations.csv").drop(columns=["index", "source_stem"]).set_index("source").transpose().reset_index()
    geo_counts = md.get_geo_locations().drop(columns=["index", "source_stem"]).set_index("source").transpose().reset_index()

    if geo_counts[study].isnull().values.any():
        return display(
            Markdown(
                "Geographical Coverage is currently unavailable for {}.".format(study)
                    ))

    else:
        # read polygons from UK geojson
        geo_polys = gpd.read_file("regions.geojson")

        geo_data = geo_polys.merge(geo_counts, left_on="id", right_on="index")

        # change to mercator projection
        geo_data2 = geo_data.to_crs(epsg=3857)

        # Explodes multi-polygons into polygons
        geo_data2 = geo_data2.explode(index_parts=True).reset_index(drop=True)

        # Extracts coordinates
        def get_coords(geometry):
            """Extract simple x and y lists from a single Polygon."""
            if geometry.geom_type == 'Polygon':
                x, y = geometry.exterior.xy
                return list(x), list(y)
            return [], []

        def generate_custom_palette(steps=256):
            # Start: White (255, 255, 255)
            # End: Midnight Blue (25, 25, 112)
            start_rgb = (255, 255, 255)
            end_rgb = (25, 25, 112)
            
            palette = []
            for i in range(steps):
                # Linear interpolation between start and end for each channel
                r = int(start_rgb[0] + (end_rgb[0] - start_rgb[0]) * i / (steps - 1))
                g = int(start_rgb[1] + (end_rgb[1] - start_rgb[1]) * i / (steps - 1))
                b = int(start_rgb[2] + (end_rgb[2] - start_rgb[2]) * i / (steps - 1))
                
                # Convert to hex string and append
                palette.append(f"#{r:02x}{g:02x}{b:02x}")
                
            return palette

        # Create the list
        ukllc_palette = generate_custom_palette()

        coords = geo_data2['geometry'].apply(get_coords)
        geo_data2['xs'] = coords.apply(lambda x: x[0])
        geo_data2['ys'] = coords.apply(lambda x: x[1])

        # drop geometry
        df_final = pd.DataFrame(geo_data2.drop(columns=["geometry"]))
        source = ColumnDataSource(df_final)

        # Plotting stuff
        color_mapper = LinearColorMapper(palette=ukllc_palette, 
                                        low=df_final[study].min(), 
                                        high=df_final[study].max())
        p = figure(title="Geographical coverage of {} participants".format(study), 
                tools="pan,wheel_zoom,reset,save",
                x_axis_location=None, y_axis_location=None,
                x_axis_type="mercator", y_axis_type="mercator",
                match_aspect=True) # match_aspect prevents the UK from looking 'stretched'

        p.patches('xs', 'ys', source=source,
                fill_color={'field': study, 'transform': color_mapper}, 
                fill_alpha=0.8,
                line_color="black", 
                line_width=0.5)

        # hovertool
        hover = HoverTool(tooltips=[
            ("Region", "@id"),
            ("Participants", "@{}".format(study))
        ])
        p.add_tools(hover)

        # color bar legend
        color_bar = ColorBar(color_mapper=color_mapper, label_standoff=12, border_line_color=None, location=(0,0))
        p.add_layout(color_bar, 'right')

        p.grid.grid_line_color = None
        show(p)

In [ ]:
geo_counts = pd.read_csv("geo_locations.csv").drop(columns=["index", "source_stem"]).set_index("source").transpose().reset_index()

In [ ]:
if geo_counts["NICOLA"].isnull().values.any():
    print("True")
else:
    print("False")

In [ ]:
md.get_place_var_info()

In [ ]:
API_KEY = os.environ['FASTAPI_KEY']

def get_geo_locations():
    url = ('https://metadata-api-4a09f2833a54.herokuapp.com/geo-locations/')
    r = requests.get(url, headers={'access_token': API_KEY})

    col_rename = {
        "east_of_england": "East of England",
        "south_east": "South East",
        "north_west": "North West",
        "east_midlands": "East Midlands",
        "west_midlands": "West Midlands",
        "south_west": "South West",
        "london": "London",
        "yorkshire_and_the_humber": "Yorkshire and The Humber",
        "north_east": "North East",
        "wales": "Wales",
        "scotland": "Scotland",
        "northern_ireland": "Northern Ireland"
        }
    
    return pd.json_normalize(json.loads(r.text)).rename(columns=col_rename)

In [3]:
with open(filename) as ff:
    nb_in = nbformat.read(ff, nbformat.NO_CONVERT)
    
ep = ExecutePreprocessor(timeout=600, kernel_name='python3')

nb_out = ep.preprocess(nb_in)

In [3]:
filename = '..//lps_data//lps_profiles//exceed.ipynb'
with open(filename) as ff:
    nb_in = nbformat.read(ff, nbformat.NO_CONVERT)

ep = ExecutePreprocessor(timeout=600, kernel_name='python3')
nb_out = ep.preprocess(nb_in)
nbformat.write(nb_out[0], filename)

In [ ]:
study = "ukhls"

files = []
for root, dirnames, filenames in os.walk("..//lps_data//datasets"):
    for file in filenames:
        abspath = os.path.abspath(os.path.join(root, file))
        files.append(abspath)

for i in tqdm.tqdm([i for i in files if i.split("\\")[-3] == study]): 
    print(f"re-running NB {i}...")
    filename = i
    with open(filename) as ff:
        nb_in = nbformat.read(ff, nbformat.NO_CONVERT)

    ep = ExecutePreprocessor(timeout=600, kernel_name='python3')
    nb_out = ep.preprocess(nb_in)
    nbformat.write(nb_out[0], filename)
    print(f"Completed re-run of NB {i}!")

  0%|          | 0/25 [00:00<?, ?it/s]

re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\a_indresp.ipynb...

  4%|▍         | 1/25 [00:21<08:33, 21.41s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\a_indresp.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\b_indresp.ipynb...

  8%|▊         | 2/25 [00:41<07:51, 20.49s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\b_indresp.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\ca_indresp_w.ipynb...

 12%|█▏        | 3/25 [01:02<07:34, 20.66s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\ca_indresp_w.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\cb_indresp_w.ipynb...

 16%|█▌        | 4/25 [01:21<07:03, 20.16s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\cb_indresp_w.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\cc_indresp_w.ipynb...

 20%|██        | 5/25 [01:41<06:42, 20.12s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\cc_indresp_w.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\cd_indresp_w.ipynb...

 24%|██▍       | 6/25 [02:00<06:16, 19.80s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\cd_indresp_w.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\ce_indresp_w.ipynb...

 28%|██▊       | 7/25 [02:21<06:00, 20.04s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\ce_indresp_w.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\cf_indresp_w.ipynb...

 32%|███▏      | 8/25 [02:41<05:42, 20.17s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\cf_indresp_w.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\cg_indresp_w.ipynb...

 36%|███▌      | 9/25 [03:01<05:19, 19.98s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\cg_indresp_w.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\ch_indresp_w.ipynb...

 40%|████      | 10/25 [03:20<04:57, 19.80s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\ch_indresp_w.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\ch_serology.ipynb...

 44%|████▍     | 11/25 [03:41<04:39, 19.99s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\ch_serology.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\ci_indresp_w.ipynb...

 48%|████▊     | 12/25 [04:01<04:22, 20.15s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\ci_indresp_w.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\c_indresp.ipynb...

 52%|█████▏    | 13/25 [04:25<04:13, 21.13s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\c_indresp.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\d_indresp.ipynb...

 56%|█████▌    | 14/25 [04:46<03:53, 21.27s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\d_indresp.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\e_indresp.ipynb...

 60%|██████    | 15/25 [05:07<03:32, 21.20s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\e_indresp.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\f_indresp.ipynb...

 64%|██████▍   | 16/25 [05:30<03:15, 21.77s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\f_indresp.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\g_indresp.ipynb...

 68%|██████▊   | 17/25 [05:52<02:54, 21.78s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\g_indresp.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\h_indresp.ipynb...

 72%|███████▏  | 18/25 [06:13<02:30, 21.46s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\h_indresp.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\i_indresp.ipynb...

 76%|███████▌  | 19/25 [06:36<02:12, 22.05s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\i_indresp.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\j_indresp.ipynb...

 80%|████████  | 20/25 [06:59<01:50, 22.19s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\j_indresp.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\k_indresp.ipynb...

 84%|████████▍ | 21/25 [07:22<01:29, 22.43s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\k_indresp.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\l_indresp.ipynb...

 88%|████████▊ | 22/25 [07:43<01:06, 22.22s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\l_indresp.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\ukhls_datasets.ipynb...

 92%|█████████▏| 23/25 [07:55<00:37, 18.98s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\ukhls_datasets.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\xbaseline.ipynb...

 96%|█████████▌| 24/25 [08:17<00:19, 19.82s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\xbaseline.ipynb!
re-running NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\xsample.ipynb...

100%|██████████| 25/25 [09:18<00:00, 22.35s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\gb_api_switch\Guidebook\ukllc_book\docs\lps_data\datasets\ukhls\datasets\xsample.ipynb!

In [4]:
def get_place_var_info():
    url = (api_url + 'place-var-info/')
    r = requests.get(url, headers={'access-token': API_KEY})
    return pd.json_normalize(json.loads(r.text))

In [9]:
url = (api_url + 'freeze-profile/')
r = requests.get(url, headers={'access-token': API_KEY})
r.status_code

404

In [23]:
def get_place_dataset_info():
    url = (api_url + "place-dataset-info/")
    r = requests.get(url, headers={'access-token': API_KEY})
    return pd.json_normalize(json.loads(r.text))

In [12]:
api_url = "https://mms-production-3b476d9d2c44.herokuapp.com/meta/api/"
url = (api_url + 'place-var-info/')
r = requests.get(url, headers={'access-token': API_KEY})
r.status_code

500

In [4]:
def get_table_vars(source, table):
    url = (api_url + f'datasets/{source}/{table}')
    r = requests.get(url, headers={'access-token': API_KEY})
    return pd.json_normalize(json.loads(r.text))

In [5]:
get_table_vars("alspac", "serology1m")

,index,dataset_version_id,dataset_id,data_source_id,variable_name,variable_label,value,value_label
0,0,70,9,7,avail_from_dt,label not available,None,None
1,1,70,9,7,serom_0001a,Participant sent a consent invitation: SERO,-9999,Consent withdrawn
2,2,70,9,7,serom_0001a,Participant sent a consent invitation: SERO,-1,Missing
3,3,70,9,7,serom_0001a,Participant sent a consent invitation: SERO,0,No
4,4,70,9,7,serom_0001a,Participant sent a consent invitation: SERO,1,Yes
...,...,...,...,...,...,...,...,...
87,87,70,9,7,serom_9651,Age sample received (months): SERO,-1,Missing
88,88,70,9,7,serom_mult_mum,Is a duplicate pregnancy - Remove if only look...,-9999,Consent withdrawn
89,89,70,9,7,serom_mult_mum,Is a duplicate pregnancy - Remove if only look...,1,"Yes, drop these mult mums"
90,90,70,9,7,serom_mult_mum,Is a duplicate pregnancy - Remove if only look...,2,"No, keep all these cases"
91,91,70,9,7,study_id_e,label not available,None,None

In [2]:
def get_place_var_info():
    url = (api_url + 'place-var-info/')
    r = requests.get(url, headers={'access-token': API_KEY})
    return pd.json_normalize(json.loads(r.text))

In [3]:
get_place_var_info()

,dataset_id,data_source_id,variable,owner,date_range,index,category,dataset
0,425,23,ah3blue,Open Street Map,2021,0,Environment,ahah_geo_indicators_england_wales
1,425,23,ah3blue,Open Street Map,2021,1,Environment,ahah_geo_indicators_england_wales
2,425,23,ah3dent,NHS England,2022,2,Health,ahah_geo_indicators_england_wales
3,425,23,ah3dent,NHS England,2022,3,Health,ahah_geo_indicators_england_wales
4,425,23,ah3ffood,Other,2019,4,Retail,ahah_geo_indicators_england_wales
...,...,...,...,...,...,...,...,...
2415,424,23,postcode_e,Longitudinal Population Studies (generic),None,2415,Geography,traffic_noise_england_wales_pc
2416,424,23,region,Office for National Statistics,2011,2416,Geography,traffic_noise_england_wales_pc
2417,424,23,region,Office for National Statistics,2011,2417,Geography,traffic_noise_england_wales_pc
2418,424,23,uprn_e,University of Leicester,None,2418,Geography,traffic_noise_england_wales_pc
2419,424,23,uprn_e,University of Leicester,None,2419,Geography,traffic_noise_england_wales_pc

In [15]:
def get_nhse_cohort_counts(ds: str) -> pd.DataFrame:
    """Returns cohort counts per study for a given NHSE dataset

    Args:
        ds (str): NHSE dataset name e.g. "IAPT" or "HESCC"

    Returns:
        DF: dataframe of cohort participant counts
    """

    url = (api_url + "nhs-dataset-counts/"
           + "?table={}".format(ds))
    r = requests.get(url, headers={'access-token': API_KEY})
    data = r.text
    pj = json.loads(data)
    return pd.json_normalize(
        pj
        ).sort_values(
            by="dataset", ascending=False
            ).drop_duplicates(
                subset=[
                    "dataset_stem", 
                    "cohort"
                    ]
                    ).sort_values(
                        by="cohort"
                        )

In [23]:
def get_nhs_gb_info(ds: str) -> pd.DataFrame:
    """Returns additional information for NHSE datasets not in "datasets"
    endpoint for GB pages
    NOTE: endpoint and table may be removed in the future

    Args:
        ds (str): dataset name e.g. IAPT or HESCC

    Returns:
        pd.DataFrame: additional info for dataset needed for GB
    """
    req = requests.get(
        api_url + "nhs-datasets-gb/" + 
        "?Name_of_dataset_in_TRE={}".format(ds),
        headers={'access-token': API_KEY})
    
    df = pd.json_normalize(json.loads(req.text))
    return df[
        ["Name_of_dataset_in_TRE",
         "Keywords",
         "Key_link",
         "Geographical_coverage",
         "Specific_restrictions_to_data_use",
         "Owner"]
               ].rename(columns={"Name_of_dataset_in_TRE": "table"})

In [25]:
def get_md_api_ss() -> pd.DataFrame:
    """Returns all series metadata from MD API

    Returns:
        pd.DataFrame: DF of all series metadata
    """

    r_d = requests.get(
        api_url + "source",
        headers={'access-token': API_KEY})

    # return error message if API response != 200
    try:
        r_d.raise_for_status()

    except requests.exceptions.HTTPError as err:
        return "HTTP Error: " + str(err)

    return pd.DataFrame(json.loads(r_d.text))

In [29]:
def get_md_api_profiles() -> pd.DataFrame:
    """Returns all cohort profile papers for all LPS

    Returns:
        pd.DataFrame: DF of cohort profile papers
    """

    r_d = requests.get(
        api_url + "all-source-profiles",
        headers={'access-token': API_KEY})

    # return error message if API response != 200
    try:
        r_d.raise_for_status()

    except requests.exceptions.HTTPError as err:
        return "HTTP Error: " + str(err)

    return pd.DataFrame(json.loads(r_d.text))

In [31]:
def get_md_api_avg_ages() -> pd.DataFrame:
    """Returns average participant ages for all LPS

    Returns:
        pd.DataFrame: DF of average ages for all LPS (0 for AIRWAVE & UKREACH)
    """

    r_d = requests.get(
        api_url + "all-source-ages",
        headers={'access-token': API_KEY.strip()})

    # return error message if API response != 200
    try:
        r_d.raise_for_status()

    except requests.exceptions.HTTPError as err:
        return "HTTP Error: " + str(err)

    return pd.DataFrame(json.loads(r_d.text))

In [35]:
def get_md_api_dss() -> pd.DataFrame:
    """Returns all metadata for all datasets in /all-datasets endpoing in API

    Returns:
        pd.DataFrame: DF of all dataset metadata
    """

    r_d = requests.get(
        api_url + "all-datasets",
        headers={'access-token': API_KEY.strip()})

    # return error message if API response != 200
    try:
        r_d.raise_for_status()

    except requests.exceptions.HTTPError as err:
        return "HTTP Error: " + str(err)

    dsall = pd.DataFrame(json.loads(r_d.text))
    return dsall[dsall["table"] != "Custom"]

In [39]:
def get_md_api_dsvs() -> pd.DataFrame:
    """Returns all dataset versions from MD DB

    Returns:
        DF: dataframe of all dataset versions from MD DB
    """

    r_d = requests.get(
      api_url + "all-datasets-versions",
      headers={'access-token': API_KEY.strip()})

    # return error message if API response != 200
    try:
        r_d.raise_for_status()

    except requests.exceptions.HTTPError as err:
        return "HTTP Error: " + str(err)

    dsall = pd.DataFrame(json.loads(r_d.text))

    # return dsall[(dsall["source"] != "nhsd") & (dsall["source"] != "GEO")]
    return dsall

In [6]:
def get_num_vars(source: str, dataset: str) -> int:
    """Reads dataset metadata endpoint to get number of variables

    Args:
        source (str): source e.g. "ALSPAC" or "nhsd"
        table_name (str): table name e.g. "serology1m" or "MORTALITY"

    Returns:
        int: number of variables
    """

    response = requests.get(
        api_url + f'datasets/{source}/{dataset}',
        headers={'access-token': API_KEY.strip()})

    return len(pd.DataFrame(json.loads(response.text))
        ["variable_name"].unique())

In [7]:
get_num_vars("alspac", "serology1m")

20

In [100]:
response = requests.get(
        api_url + "datasets/" + '{source_and_table_name}?source=alspac"&table_name=serology1m',
        headers={'access-token': API_KEY.strip()})
response.status_code

404

In [95]:
api_url + "datasets/" + "{source_and_table_name}?source=alspac&table_name=serology1m"

'https://mms-production-3b476d9d2c44.herokuapp.com/meta/api/datasets/{source_and_table_name}?source=alspac&table_name=serology1m'

In [ ]:
def get_md_api_frz_link_nhse() -> pd.DataFrame:
    """Returns dataframe of all freeze linkage rates (NHSE only for now)

    Returns:
        pd.DataFrame: dataframe of all freeze linkage metrics
    """
    r_d = requests.get(
            api_url + 
            "freeze-linkage-nhse/",
            headers={'access-token': API_KEY.strip()})

    try:
        r_d.raise_for_status()

    except requests.exceptions.HTTPError as err:
        return "HTTP Error: " + str(err)

    return pd.DataFrame(json.loads(r_d.text))

In [8]:
def get_freeze_profile():
    """Returns dataframe of freeze profile metrics (sex, age, ethnicity)

    Returns:
        pd.DataFrame: dataframe of freeze profile metrics
    """
    r_d = requests.get(
            api_url +
            "freeze-profile/",
            headers={'access-token': API_KEY.strip()})

    try:
        r_d.raise_for_status()

    except requests.exceptions.HTTPError as err:
        return "HTTP Error: " + str(err)

    return pd.DataFrame(json.loads(r_d.text))

In [9]:
get_freeze_profile()

Empty DataFrame
Columns: []
Index: []

In [ ]:
def get_place_var_info():
    url = (api_url + 'place-var-info/')
    r = requests.get(url, headers={'access-token': API_KEY})
    return pd.json_normalize(json.loads(r.text))

In [33]:
def metrics(dataset):
    """Returns cohort counts for datasets and auxiliary dataset
        if applicable (e.g. for IAPT and MHSDS)

    Args:
        self.dataset (str): dataset e.g. IAPT or HESCC

    Returns:
        str: "TBC" for any datasets not in cohort-count API
        OR
        figure: bokeh datacube of cohort counts
    """

    output_notebook(hide_banner=True)
    df = md.get_md_api_dsvs()
    def fix_hes(x):
        if x in ["HESAPC_acp", "HESAPC_mat"]:
            return x.upper()
        else:
            return x
    df["table"] = df["table"].apply(lambda x: fix_hes(x))
    df = df[(df["source"] == "NHSE") & (df["table"].str.startswith(dataset))].drop_duplicates(subset="table")

    df = df[~df["table"].isin(["MHSDS_MHS003AccommStatus", "MHSDS_MHS104RTT", "MHSDS_MHS301GroupSession", "MHSDS_MHS901StaffDetails", "CSDS_group_sessions"])]

    if dataset in ["HESAPC", "HESOP", "HESAE"]:
        df = df[df["table"] == dataset]

    tbl_names = []
    metrics_tables = []

    for i in range(0, len(df)):
        dfcc = md.get_nhse_cohort_counts(df.iloc[i]["table"])
        dfcc = dfcc[~dfcc['cohort'].isin(['GENSCOT', 'NICOLA', 'SABRE'])]
        tbl_names += len(dfcc) * [df.iloc[i]["table"]]
        dfcc["count"] = dfcc["count"].replace("<10", np.nan).astype(float)
        metrics_tables.append(dfcc)

    source = ColumnDataSource(data=dict(
        d0=tbl_names,
        d1=pd.concat(metrics_tables)["cohort"].to_list(),
        px=pd.concat(metrics_tables)["count"].to_list(),
    ))

    target = ColumnDataSource(data=dict(row_indices=[], labels=[]))

    formatter = StringFormatter(font_style='bold')

    columns = [
        TableColumn(field='d1', title='{} Dataset'.format(dataset), width=80, sortable=False, formatter=formatter),
        TableColumn(field='px', title='Participant Count', width=40, sortable=False, formatter=StringFormatter(text_align='right', nan_format='<10')),
    ]

    grouping = [
        GroupingInfo(getter='d0', aggregators=[SumAggregator(field_='px')]),
    ]

    cube = DataCube(source=source, columns=columns, grouping=grouping, target=target)
    display(Markdown("Click on the plus sign to see the number of participants represented in each dataset."))
    display(Markdown("**Table 2:** Participants from each LPS represented in the {} dataset in the UK LLC TRE. **Note:** Individual cohort counts of less than 10 are suppressed to <10 and excluded from total participant counts for datasets.".format(dataset)))
    show(cube)

In [ ]:
metrics("HESAE")

Click on the plus sign to see the number of participants represented in each dataset.

**Table 2:** Participants from each LPS represented in the HESAE dataset in the UK LLC TRE. **Note:** Individual cohort counts of less than 10 are suppressed to <10 and excluded from total participant counts for datasets.

In [23]:
output_notebook(hide_banner=True)
df = md.get_md_api_dsvs()
def fix_hes(x):
    if x in ["HESAPC_acp", "HESAPC_mat"]:
        return x.upper()
    else:
        return x
df["table"] = df["table"].apply(lambda x: fix_hes(x))
df = df[(df["source"] == "nhsd") & (df["table"].str.startswith(dataset))].drop_duplicates(subset="table")

df = df[~df["table"].isin(["MHSDS_MHS003AccommStatus", "MHSDS_MHS104RTT", "MHSDS_MHS301GroupSession", "MHSDS_MHS901StaffDetails", "CSDS_group_sessions"])]

if dataset in ["HESAPC", "HESOP", "HESAE"]:
    df = df[df["table"] == dataset]

tbl_names = []
metrics_tables = []

for i in range(0, len(df)):
    dfcc = md.get_nhse_cohort_counts(df.iloc[i]["table"])
    dfcc = dfcc[~dfcc['cohort'].isin(['GENSCOT', 'NICOLA', 'SABRE'])]
    tbl_names += len(dfcc) * [df.iloc[i]["table"]]
    dfcc["count"] = dfcc["count"].replace("<10", np.nan).astype(float)
    metrics_tables.append(dfcc)

# source = ColumnDataSource(data=dict(
#     d0=tbl_names,
#     d1=pd.concat(metrics_tables)["cohort"].to_list(),
#     px=pd.concat(metrics_tables)["count"].to_list(),
# ))

# target = ColumnDataSource(data=dict(row_indices=[], labels=[]))

# formatter = StringFormatter(font_style='bold')

# columns = [
#     TableColumn(field='d1', title='{} Dataset'.format(self.dataset), width=80, sortable=False, formatter=formatter),
#     TableColumn(field='px', title='Participant Count', width=40, sortable=False, formatter=StringFormatter(text_align='right', nan_format='<10')),
# ]

# grouping = [
#     GroupingInfo(getter='d0', aggregators=[SumAggregator(field_='px')]),
# ]

# cube = DataCube(source=source, columns=columns, grouping=grouping, target=target)
# display(Markdown("Click on the plus sign to see the number of participants represented in each dataset."))
# display(Markdown("**Table 2:** Participants from each LPS represented in the {} dataset in the UK LLC TRE. **Note:** Individual cohort counts of less than 10 are suppressed to <10 and excluded from total participant counts for datasets.".format(self.dataset)))
# show(cube)

In [26]:
df = md.get_md_api_dsvs()
df

,dataset_version_id,dataset_id,data_source_id,source,values_table,index,description_table,version_date,num_rows,table_full,table,version_num,num_columns,num_participants
0,317,1,19,AIRWAVE,clinic_baseline_v0001_values_20250917,0,clinic_baseline_v0001_description_20250917,20250917.0,46205.0,clinic_baseline_v0001_20250917,clinic_baseline,v0001,125.0,45329.0
1,316,1,19,AIRWAVE,clinic_baseline_v0002_values_20250922,1,clinic_baseline_v0002_description_20250922,20250922.0,46205.0,clinic_baseline_v0002_20250922,clinic_baseline,v0002,129.0,45329.0
2,315,2,19,AIRWAVE,clinic_followup_v0001_values_20250922,2,clinic_followup_v0001_description_20250922,20250922.0,22183.0,clinic_followup_v0001_20250922,clinic_followup,v0001,110.0,18893.0
3,314,7,19,AIRWAVE,cogtest_baseline_summary_v0001_values_20251017,3,cogtest_baseline_summary_v0001_description_202...,20251017.0,31466.0,cogtest_baseline_summary_v0001_20251017,cogtest_baseline_summary,v0001,32.0,31459.0
4,313,3,19,AIRWAVE,cogtest_post2020_details_v0001_values_20251003,4,cogtest_post2020_details_v0001_description_202...,20251003.0,1048697.0,cogtest_post2020_details_v0001_20251003,cogtest_post2020_details,v0001,14.0,4087.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,49,395,25,UKLLC,study_permissions_v0001_values_20250122,771,study_permissions_v0001_description_20250122,20250122.0,326421.0,study_permissions_v0001_20250122,study_permissions,v0001,14.0,326421.0
772,48,395,25,UKLLC,study_permissions_v0001_values_20250407,772,study_permissions_v0001_description_20250407,20250407.0,332157.0,study_permissions_v0001_20250407,study_permissions,v0001,14.0,332157.0
773,47,395,25,UKLLC,study_permissions_v0001_values_20250901,773,study_permissions_v0001_description_20250901,20250901.0,407370.0,study_permissions_v0001_20250901,study_permissions,v0001,14.0,407370.0
774,46,395,25,UKLLC,study_permissions_v0001_values_20250903,774,study_permissions_v0001_description_20250903,20250903.0,414912.0,study_permissions_v0001_20250903,study_permissions,v0001,14.0,414912.0
775,45,395,25,UKLLC,study_permissions_v0001_values_20251123,775,study_permissions_v0001_description_20251123,20251123.0,573324.0,study_permissions_v0001_20251123,study_permissions,v0001,14.0,573324.0

In [32]:
dc_env = "PROD"

# DataCite API test env variables
if dc_env == "TEST":
    ID = 'WHRN.UKLLCTEST'
    pw = os.environ['DATACITE_TEST_PW']
    url_doi = "api.test.datacite.org"
    prefix = "10.83126"
# DataCite API prod  env variables
elif dc_env == "PROD":
    ID = 'VHFS.UKLLC'
    pw = os.environ['DATACITE_PROD_PW']
    url_doi = "api.datacite.org"
    prefix = "10.71760"

headers_doi = {
    "accept": "application/vnd.api+json",
    "content-type": "application/json",
}


def get_doi_datasets2() -> pd.DataFrame:
    """Returns UK LLC dataset DOIs

    Returns:
        pd.DataFrame: DF of UK LLC dataset version DOIs
    """

    resp_doi_ds_get = requests.get(
        "https://{}/dois?prefix={}&"
        "resource-type-id=dataset&&page[size]=1000&"
        "fields[dois]=creators%2Ctitles%2Cversion%2Cstate%2Cidentifiers%2Curl".format(url_doi, prefix),
        headers={
            "accept": "application/vnd.api+json",
                },
        auth=(ID, pw)
        )

    doi_datasets = resp_doi_ds_get.json()

    doi_dss = pd.json_normalize(doi_datasets['data'])
    if len(doi_dss) == 0:
        return doi_dss.reindex(doi_dss.columns.union(
            ["id",
             "state",
             "attributes.identifiers",
             "creators",
             "title",
             "source_table"]
            ), axis=1)

    else:
        doi_dss['creators'] = doi_dss['attributes.creators']\
            .apply(lambda x: x[0]['name'])
        doi_dss['title'] = doi_dss['attributes.titles']\
            .apply(lambda x: x[0]['title'])

        doi_dss = doi_dss.rename(columns={"attributes.state": "state"})

        return doi_dss.drop(
            [
                'attributes.creators', 'type'
            ],
            axis=1
            )

In [27]:
doi_ds = get_doi_datasets2()

In [28]:
doi_ds["source_table"] = doi_ds["attributes.titles"].apply(lambda x: x[1]["title"])

In [29]:
doi_ds2 = doi_ds[(doi_ds["source_table"].str.startswith("NHSE")) | (doi_ds["source_table"].str.startswith("UKLLC"))]

In [30]:
doi_ds_nhse = doi_ds2[doi_ds2["source_table"].str.startswith("NHSE")]

In [36]:
row = doi_ds_nhse.iloc[0]

In [37]:
row["id"]

'10.71760/ukllc-dataset-00379-03'

In [34]:
doi_ds_nhse.iloc[0]["attributes.url"].replace("%20", "_")

'https://guidebook.ukllc.ac.uk/docs/linked_health_data/nhs_england/covid_datasets/ielisa/ielisa'

In [51]:
def change_nhse_url(row):

    time.sleep(3)

    print(f"""Changing DOI {row["id"]}, ({row["source_table"]})""")

    url_ds = ("https://" + url_doi + "/dois/" + row["id"])

    payload = { "data": {
            "attributes": { "url": row["attributes.url"].replace("%20", "_")},
            "type": "dois"
        } }
    headers = {
        "accept": "application/vnd.api+json",
        "content-type": "application/json"
    }

    response = requests.put(
        url_ds, 
        json=payload, 
        headers=headers,
        auth=(ID, pw))

    print(response.status_code)
    return response.status_code

In [52]:
doi_ds_nhse["doi_changed?"] = doi_ds_nhse.apply(lambda row: change_nhse_url(row), axis=1)

Changing DOI 10.71760/ukllc-dataset-00379-03, (NHSE_IELISA)
200
Changing DOI 10.71760/ukllc-dataset-00375-03, (NHSE_PCM)
200
Changing DOI 10.71760/ukllc-dataset-00360-03, (NHSE_IAPT)
200
Changing DOI 10.71760/ukllc-dataset-00378-03, (NHSE_NPEX)
200
Changing DOI 10.71760/ukllc-dataset-00392-03, (NHSE_COVIDSGSS)
200
Changing DOI 10.71760/ukllc-dataset-00381-02, (NHSE_CVAR)
200
Changing DOI 10.71760/ukllc-dataset-00364-03, (NHSE_CSDS)
200
Changing DOI 10.71760/ukllc-dataset-00364-02, (NHSE_CSDS)
200
Changing DOI 10.71760/ukllc-dataset-00365-03, (NHSE_HESAPC_ACP)
200
Changing DOI 10.71760/ukllc-dataset-00365-02, (NHSE_HESAPC_ACP)
200
Changing DOI 10.71760/ukllc-dataset-00365-01, (NHSE_HESAPC_ACP)
200
Changing DOI 10.71760/ukllc-dataset-00373-03, (NHSE_HESAPC_MAT)
200
Changing DOI 10.71760/ukllc-dataset-00373-02, (NHSE_HESAPC_MAT)
200
Changing DOI 10.71760/ukllc-dataset-00373-01, (NHSE_HESAPC_MAT)
200
Changing DOI 10.71760/ukllc-dataset-00375-02, (NHSE_PCM)
200
Changing DOI 10.71760/ukllc-dataset-00375-01, (NHSE_PCM)
200
Changing DOI 10.71760/ukllc-dataset-00359-01, (NHSE_ECDS)
200
Changing DOI 10.71760/ukllc-dataset-00359-03, (NHSE_ECDS)
200
Changing DOI 10.71760/ukllc-dataset-00360-02, (NHSE_IAPT)
200
Changing DOI 10.71760/ukllc-dataset-00359-02, (NHSE_ECDS)
200
Changing DOI 10.71760/ukllc-dataset-00361-03, (NHSE_HESAPC)
200
Changing DOI 10.71760/ukllc-dataset-00362-02, (NHSE_HESAE)
200
Changing DOI 10.71760/ukllc-dataset-00361-02, (NHSE_HESAPC)
200
Changing DOI 10.71760/ukllc-dataset-00362-03, (NHSE_HESAE)
200
Changing DOI 10.71760/ukllc-dataset-00362-01, (NHSE_HESAE)
200
Changing DOI 10.71760/ukllc-dataset-00361-01, (NHSE_HESAPC)
200
Changing DOI 10.71760/ukllc-dataset-00363-02, (NHSE_HESOP)
200
Changing DOI 10.71760/ukllc-dataset-00363-01, (NHSE_HESOP)
200
Changing DOI 10.71760/ukllc-dataset-00363-03, (NHSE_HESOP)
200
Changing DOI 10.71760/ukllc-dataset-00366-01, (NHSE_MORTALITY_20220302)
200
Changing DOI 10.71760/ukllc-dataset-00368-02, (NHSE_MORTALITY_20240523)
200
Changing DOI 10.71760/ukllc-dataset-00370-02, (NHSE_MORTALITY_20230302)
200
Changing DOI 10.71760/ukllc-dataset-00369-02, (NHSE_MORTALITY_20240424)
200
Changing DOI 10.71760/ukllc-dataset-00367-01, (NHSE_MORTALITY_20220715)
200
Changing DOI 10.71760/ukllc-dataset-00366-02, (NHSE_MORTALITY_20220302)
200
Changing DOI 10.71760/ukllc-dataset-00371-02, (NHSE_MORTALITY_20220106)
200
Changing DOI 10.71760/ukllc-dataset-00371-01, (NHSE_MORTALITY_20220106)
200
Changing DOI 10.71760/ukllc-dataset-00372-01, (NHSE_MORTALITY_20220716)
200
Changing DOI 10.71760/ukllc-dataset-00374-02, (NHSE_CHESS)
200
Changing DOI 10.71760/ukllc-dataset-00374-01, (NHSE_CHESS)
200
Changing DOI 10.71760/ukllc-dataset-00377-03, (NHSE_MHSDS)
200
Changing DOI 10.71760/ukllc-dataset-00376-03, (NHSE_CVS)
200
Changing DOI 10.71760/ukllc-dataset-00377-01, (NHSE_MHSDS)
200
Changing DOI 10.71760/ukllc-dataset-00376-02, (NHSE_CVS)
200
Changing DOI 10.71760/ukllc-dataset-00377-02, (NHSE_MHSDS)
200
Changing DOI 10.71760/ukllc-dataset-00376-01, (NHSE_CVS)
200
Changing DOI 10.71760/ukllc-dataset-00378-02, (NHSE_NPEX)
200
Changing DOI 10.71760/ukllc-dataset-00378-01, (NHSE_NPEX)
200
Changing DOI 10.71760/ukllc-dataset-00379-02, (NHSE_IELISA)
200
Changing DOI 10.71760/ukllc-dataset-00379-01, (NHSE_IELISA)
200
Changing DOI 10.71760/ukllc-dataset-00380-02, (NHSE_HESCC)
200
Changing DOI 10.71760/ukllc-dataset-00380-03, (NHSE_HESCC)
200
Changing DOI 10.71760/ukllc-dataset-00382-02, (NHSE_GDPPR)
200
Changing DOI 10.71760/ukllc-dataset-00380-01, (NHSE_HESCC)
200
Changing DOI 10.71760/ukllc-dataset-00381-01, (NHSE_CVAR)
200
Changing DOI 10.71760/ukllc-dataset-00382-03, (NHSE_GDPPR)
200
Changing DOI 10.71760/ukllc-dataset-00382-01, (NHSE_GDPPR)
200
Changing DOI 10.71760/ukllc-dataset-00383-02, (NHSE_CANCER_20240523)
200
Changing DOI 10.71760/ukllc-dataset-00384-02, (NHSE_CANCER_20240424)
200
Changing DOI 10.71760/ukllc-dataset-00391-02, (NHSE_CANCER_20220106)
200
Changing DOI 10.71760/ukllc-dataset-00390-02, (NHSE_CANCER_20220302)
200
Changing DOI 10.71760/ukllc-dataset-00386-02, (NHSE_CANCER_20221228)
200
Changing DOI 10.71760/ukllc-dataset-00385-02, (NHSE_CANCER_20230302)
200
Changing DOI 10.71760/ukllc-dataset-00386-01, (NHSE_CANCER_20221228)
200
Changing DOI 10.71760/ukllc-dataset-00387-01, (NHSE_CANCER_20221110)
200
Changing DOI 10.71760/ukllc-dataset-00389-01, (NHSE_CANCER_20220715)
200
Changing DOI 10.71760/ukllc-dataset-00390-01, (NHSE_CANCER_20220302)
200
Changing DOI 10.71760/ukllc-dataset-00391-01, (NHSE_CANCER_20220106)
200
Changing DOI 10.71760/ukllc-dataset-00388-01, (NHSE_CANCER_20220716)
200
Changing DOI 10.71760/ukllc-dataset-00392-02, (NHSE_COVIDSGSS)
200
Changing DOI 10.71760/ukllc-dataset-00394-01, (NHSE_DEMOGRAPHICS_20220106)
200
Changing DOI 10.71760/ukllc-dataset-00393-01, (NHSE_DEMOGRAPHICS_20221228)
200
Changing DOI 10.71760/ukllc-dataset-00392-01, (NHSE_COVIDSGSS)
200
Changing DOI 10.71760/ukllc-dataset-00395-02, (NHSE_DEMOGRAPHICS_20230302)
200
Changing DOI 10.71760/ukllc-dataset-00396-02, (NHSE_DEMOGRAPHICS_20240523)
200
Changing DOI 10.71760/ukllc-dataset-00401-02, (NHSE_DEMOGRAPHICS_20220302)
200
Changing DOI 10.71760/ukllc-dataset-00393-02, (NHSE_DEMOGRAPHICS_20221228)
200
Changing DOI 10.71760/ukllc-dataset-00398-01, (NHSE_DEMOGRAPHICS_20221110)
200
Changing DOI 10.71760/ukllc-dataset-00394-02, (NHSE_DEMOGRAPHICS_20220106)
200
Changing DOI 10.71760/ukllc-dataset-00397-01, (NHSE_DEMOGRAPHICS_20220716)
200
Changing DOI 10.71760/ukllc-dataset-00401-01, (NHSE_DEMOGRAPHICS_20220302)
200
Changing DOI 10.71760/ukllc-dataset-00399-02, (NHSE_DEMOGRAPHICS_20240424)
200
Changing DOI 10.71760/ukllc-dataset-00400-01, (NHSE_DEMOGRAPHICS_20220715)
200

In [53]:
doi_ds_llc = doi_ds2[doi_ds2["source_table"].str.startswith("UKLLC")]

In [81]:
row = doi_ds_llc.iloc[2]

In [82]:
row["attributes.titles"][1]["title"]

'UKLLC_nhse_patient_service_usage'

In [85]:
def change_llc_url(row):

    time.sleep(3)

    if "_rtn_" in row["attributes.titles"][1]["title"]:
        if "harmonised" in row["attributes.titles"][1]["title"]:
            url_new = row["attributes.url"].replace("ukllc_generated/datasets/lps_derived", "datasets/sociodemo_harmonised")

        elif  "comorbidity" in row["attributes.titles"][1]["title"]:
            url_new = row["attributes.url"].replace("researcher_generated/datasets", "datasets/charlson")

    else:
        url_new = row["attributes.url"].replace("ukllc_generated/datasets/linked_derived", "datasets/nhse_reference")


    print(f"""Changing DOI {row["id"]}, ({row["source_table"]})""")

    url_ds = ("https://" + url_doi + "/dois/" + row["id"])

    payload = { "data": {
            "attributes": { "url": url_new},
            "type": "dois"
        } }
    headers = {
        "accept": "application/vnd.api+json",
        "content-type": "application/json"
    }

    response = requests.put(
        url_ds, 
        json=payload, 
        headers=headers,
        auth=(ID, pw))

    print(response.status_code)
    return response.status_code

In [86]:
doi_ds_llc["doi_changed?"] = doi_ds_llc.apply(lambda row: change_llc_url(row), axis=1)

Changing DOI 10.71760/ukllc-dataset-00440-08, (UKLLC_nhse_patient_demo_mortality)
200
Changing DOI 10.71760/ukllc-dataset-00441-04, (UKLLC_nhse_lsoa11_dataset_mapping)
200
Changing DOI 10.71760/ukllc-dataset-00439-09, (UKLLC_nhse_patient_service_usage)
200
Changing DOI 10.71760/ukllc-dataset-00478-01, (UKLLC_study_permissions_20250901)
200
Changing DOI 10.71760/ukllc-dataset-00479-01, (UKLLC_study_permissions_20250903)
200
Changing DOI 10.71760/ukllc-dataset-00477-04, (UKLLC_nhse_lsoa11_dataset_mapping)
200
Changing DOI 10.71760/ukllc-dataset-00476-08, (UKLLC_nhse_patient_demo_mortality)
200
Changing DOI 10.71760/ukllc-dataset-00480-09, (UKLLC_nhse_patient_service_usage)
200
Changing DOI 10.71760/ukllc-dataset-00463-01, (UKLLC_rtn_lps_education_harmonised)
200
Changing DOI 10.71760/ukllc-dataset-00470-01, (UKLLC_study_permissions_20230309)
200
Changing DOI 10.71760/ukllc-dataset-00469-01, (UKLLC_study_permissions_20221019)
200
Changing DOI 10.71760/ukllc-dataset-00472-01, (UKLLC_study_permissions_20240910)
200
Changing DOI 10.71760/ukllc-dataset-00467-01, (UKLLC_study_permissions_20220914)
200
Changing DOI 10.71760/ukllc-dataset-00471-01, (UKLLC_study_permissions_20240726)
200
Changing DOI 10.71760/ukllc-dataset-00465-01, (UKLLC_study_permissions_20220801)
200
Changing DOI 10.71760/ukllc-dataset-00460-06, (UKLLC_nhse_patient_service_usage)
200
Changing DOI 10.71760/ukllc-dataset-00460-07, (UKLLC_nhse_patient_service_usage)
200
Changing DOI 10.71760/ukllc-dataset-00461-04, (UKLLC_nhse_patient_demo_mortality)
200
Changing DOI 10.71760/ukllc-dataset-00461-07, (UKLLC_nhse_patient_demo_mortality)
200
Changing DOI 10.71760/ukllc-dataset-00462-03, (UKLLC_nhse_lsoa11_dataset_mapping)
200
Changing DOI 10.71760/ukllc-dataset-00462-02, (UKLLC_nhse_lsoa11_dataset_mapping)
200
Changing DOI 10.71760/ukllc-dataset-00437-01, (UKLLC_rtn_lps_sociodemo_harmonised_reduced)
200
Changing DOI 10.71760/ukllc-dataset-00439-07, (UKLLC_nhse_patient_service_usage)
200
Changing DOI 10.71760/ukllc-dataset-00439-06, (UKLLC_nhse_patient_service_usage)
200
Changing DOI 10.71760/ukllc-dataset-00439-05, (UKLLC_nhse_patient_service_usage)
200
Changing DOI 10.71760/ukllc-dataset-00438-01, (UKLLC_rtn_comorbidity_scores_mar19feb20)
200
Changing DOI 10.71760/ukllc-dataset-00440-05, (UKLLC_nhse_patient_demo_mortality)
200
Changing DOI 10.71760/ukllc-dataset-00440-04, (UKLLC_nhse_patient_demo_mortality)
200
Changing DOI 10.71760/ukllc-dataset-00439-08, (UKLLC_nhse_patient_service_usage)
200
Changing DOI 10.71760/ukllc-dataset-00440-06, (UKLLC_nhse_patient_demo_mortality)
200
Changing DOI 10.71760/ukllc-dataset-00441-03, (UKLLC_nhse_lsoa11_dataset_mapping)
200
Changing DOI 10.71760/ukllc-dataset-00441-02, (UKLLC_nhse_lsoa11_dataset_mapping)
200
Changing DOI 10.71760/ukllc-dataset-00440-07, (UKLLC_nhse_patient_demo_mortality)
200
Changing DOI 10.71760/ukllc-dataset-00441-01, (UKLLC_nhse_lsoa11_dataset_mapping)
200
Changing DOI 10.71760/ukllc-dataset-00444-01, (UKLLC_study_permissions_20220122)
200
Changing DOI 10.71760/ukllc-dataset-00443-01, (UKLLC_rtn_lps_education_harmonised)
200
Changing DOI 10.71760/ukllc-dataset-00442-01, (UKLLC_rtn_lps_sociodemo_harmonised_full)
200
Changing DOI 10.71760/ukllc-dataset-00445-01, (UKLLC_study_permissions_20220412)
200
Changing DOI 10.71760/ukllc-dataset-00446-01, (UKLLC_study_permissions_20220623)
200
Changing DOI 10.71760/ukllc-dataset-00447-01, (UKLLC_study_permissions_20220801)
200
Changing DOI 10.71760/ukllc-dataset-00449-01, (UKLLC_study_permissions_20220818)
200
Changing DOI 10.71760/ukllc-dataset-00448-01, (UKLLC_study_permissions_20220811)
200
Changing DOI 10.71760/ukllc-dataset-00452-01, (UKLLC_study_permissions_20221012)
200
Changing DOI 10.71760/ukllc-dataset-00453-01, (UKLLC_study_permissions_20221019)
200
Changing DOI 10.71760/ukllc-dataset-00451-01, (UKLLC_study_permissions_20221011)
200
Changing DOI 10.71760/ukllc-dataset-00450-01, (UKLLC_study_permissions_20220914)
200
Changing DOI 10.71760/ukllc-dataset-00456-01, (UKLLC_study_permissions_20240312)
200
Changing DOI 10.71760/ukllc-dataset-00454-01, (UKLLC_study_permissions_20221201)
200
Changing DOI 10.71760/ukllc-dataset-00455-01, (UKLLC_study_permissions_20230309)
200
Changing DOI 10.71760/ukllc-dataset-00457-01, (UKLLC_study_permissions_20240726)
200
Changing DOI 10.71760/ukllc-dataset-00458-01, (UKLLC_study_permissions_20240910)
200
Changing DOI 10.71760/ukllc-dataset-00460-01, (UKLLC_study_permissions_20250407)
200
Changing DOI 10.71760/ukllc-dataset-00459-01, (UKLLC_study_permissions_20250122)
200

In [12]:
r_d = requests.get(
    api_url + "all-datasets-versions",
    headers={'access-token': API_KEY.strip()})

pd.DataFrame(json.loads(r_d.text))

,dataset_version_id,dataset_id,data_source_id,source,values_table,index,description_table,version_date,num_rows,table_full,table,version_num,num_columns,num_participants
0,317,1,19,AIRWAVE,clinic_baseline_v0001_values_20250917,0,clinic_baseline_v0001_description_20250917,20250917.0,46205.0,clinic_baseline_v0001_20250917,clinic_baseline,v0001,125.0,45329.0
1,316,1,19,AIRWAVE,clinic_baseline_v0002_values_20250922,1,clinic_baseline_v0002_description_20250922,20250922.0,46205.0,clinic_baseline_v0002_20250922,clinic_baseline,v0002,129.0,45329.0
2,315,2,19,AIRWAVE,clinic_followup_v0001_values_20250922,2,clinic_followup_v0001_description_20250922,20250922.0,22183.0,clinic_followup_v0001_20250922,clinic_followup,v0001,110.0,18893.0
3,314,7,19,AIRWAVE,cogtest_baseline_summary_v0001_values_20251017,3,cogtest_baseline_summary_v0001_description_202...,20251017.0,31466.0,cogtest_baseline_summary_v0001_20251017,cogtest_baseline_summary,v0001,32.0,31459.0
4,313,3,19,AIRWAVE,cogtest_post2020_details_v0001_values_20251003,4,cogtest_post2020_details_v0001_description_202...,20251003.0,1048697.0,cogtest_post2020_details_v0001_20251003,cogtest_post2020_details,v0001,14.0,4087.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,49,395,25,UKLLC,study_permissions_v0001_values_20250122,771,study_permissions_v0001_description_20250122,20250122.0,326421.0,study_permissions_v0001_20250122,study_permissions,v0001,14.0,326421.0
772,48,395,25,UKLLC,study_permissions_v0001_values_20250407,772,study_permissions_v0001_description_20250407,20250407.0,332157.0,study_permissions_v0001_20250407,study_permissions,v0001,14.0,332157.0
773,47,395,25,UKLLC,study_permissions_v0001_values_20250901,773,study_permissions_v0001_description_20250901,20250901.0,407370.0,study_permissions_v0001_20250901,study_permissions,v0001,14.0,407370.0
774,46,395,25,UKLLC,study_permissions_v0001_values_20250903,774,study_permissions_v0001_description_20250903,20250903.0,414912.0,study_permissions_v0001_20250903,study_permissions,v0001,14.0,414912.0
775,45,395,25,UKLLC,study_permissions_v0001_values_20251123,775,study_permissions_v0001_description_20251123,20251123.0,573324.0,study_permissions_v0001_20251123,study_permissions,v0001,14.0,573324.0

In [21]:
files = []
for root, dirnames, filenames in os.walk("..//lps_data//lps_profiles"):
    for file in filenames:
        abspath = os.path.abspath(os.path.join(root, file))
        files.append(abspath)

for i in tqdm.tqdm([i for i in files if ".ipynb" in i]): 
    print(f"re-running NB {i}...")
    filename = i
    with open(filename) as ff:
        nb_in = nbf.read(ff, nbf.NO_CONVERT)

    ep = ExecutePreprocessor(timeout=600, kernel_name='python3')
    nb_out = ep.preprocess(nb_in)
    nbf.write(nb_out[0], filename)
    print(f"Completed re-run of NB {i}!")

  0%|          | 0/23 [00:00<?, ?it/s]

re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\airwave.ipynb...

  4%|▍         | 1/23 [00:17<06:20, 17.28s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\airwave.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\alspac.ipynb...

  9%|▊         | 2/23 [00:37<06:41, 19.11s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\alspac.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\bcs70.ipynb...

 13%|█▎        | 3/23 [00:54<06:03, 18.18s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\bcs70.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\bib.ipynb...

 17%|█▋        | 4/23 [01:10<05:24, 17.07s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\bib.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\caps.ipynb...

 22%|██▏       | 5/23 [01:20<04:25, 14.75s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\caps.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\elsa.ipynb...

 26%|██▌       | 6/23 [01:34<04:03, 14.34s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\elsa.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\epicn.ipynb...

 30%|███       | 7/23 [01:47<03:43, 13.94s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\epicn.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\exceed.ipynb...

 35%|███▍      | 8/23 [02:01<03:30, 14.03s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\exceed.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\fenland.ipynb...

 39%|███▉      | 9/23 [02:20<03:39, 15.69s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\fenland.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\genscot.ipynb...

 43%|████▎     | 10/23 [02:35<03:18, 15.26s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\genscot.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\glad.ipynb...

 48%|████▊     | 11/23 [02:51<03:07, 15.59s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\glad.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\mcs.ipynb...

 52%|█████▏    | 12/23 [03:46<05:01, 27.40s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\mcs.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\ncds58.ipynb...

 57%|█████▋    | 13/23 [03:59<03:53, 23.33s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\ncds58.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\nextstep.ipynb...

 61%|██████    | 14/23 [04:12<03:00, 20.07s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\nextstep.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\nicola.ipynb...

 65%|██████▌   | 15/23 [04:24<02:21, 17.65s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\nicola.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\nihrbio_coping.ipynb...

 70%|██████▉   | 16/23 [04:37<01:54, 16.36s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\nihrbio_coping.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\nshd46.ipynb...

 74%|███████▍  | 17/23 [04:55<01:40, 16.68s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\nshd46.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\sabre.ipynb...

 78%|███████▊  | 18/23 [05:09<01:19, 15.81s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\sabre.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\teds.ipynb...

 83%|████████▎ | 19/23 [05:22<00:59, 14.97s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\teds.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\trackc19.ipynb...

 87%|████████▋ | 20/23 [05:34<00:42, 14.19s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\trackc19.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\twinsuk.ipynb...

 91%|█████████▏| 21/23 [05:47<00:27, 13.71s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\twinsuk.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\ukhls.ipynb...

 96%|█████████▌| 22/23 [06:02<00:14, 14.12s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\ukhls.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\ukreach.ipynb...

100%|██████████| 23/23 [06:16<00:00, 16.38s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\lps_profiles\ukreach.ipynb!

In [ ]:
source = "ELSA"

df = md.prep_dsvs_for_gb_pages()
df = df[df["source"] == source]

files = []
for root, dirnames, filenames in os.walk(f"..//lps_data//datasets//{source.lower()}//datasets"):
    for file in filenames:
        abspath = os.path.abspath(os.path.join(root, file))
        files.append(abspath)

# for i in tqdm.tqdm([i for i in files if ".ipynb" in i]): 
#     print(f"re-running NB {i}...")
#     filename = i
#     with open(filename) as ff:
#         nb_in = nbformat.read(ff, nbformat.NO_CONVERT)

#     ep = ExecutePreprocessor(timeout=600, kernel_name='python3')
#     nb_out = ep.preprocess(nb_in)
#     nbformat.write(nb_out[0], filename)
#     print(f"Completed re-run of NB {i}!")

In [4]:
def new_lps_ds_nb(i):

    print(f"""Creating new NB for {i["table"]}""")
    nb = nbf.v4.new_notebook()

    code_meta = {
        'tags': ['remove-input']
    }

    h1 = f"""# {i["table_name"]} ({i["source"]})"""
    c1 = f"""
    import sys
    import os
    sys.path.append(os.path.abspath('../../../../scripts/'))
    from data_doc_helper import LPSDataSet as DS, last_modified
    API_KEY = os.environ['FASTAPI_KEY']
    ds = DS("{i["source"]}", "{i["table"]}")
    last_modified()
    """
    h2 = "## 1. Summary"
    c2 = "ds.summary()"
    c3 = "ds.info_table()"
    h3 = "## 2. Version History"
    c4 = "ds.version_history()"
    h4 = "## 3. Documentation"
    c5 = "ds.documentation()"
    h5 = "## 4. Useful Syntax"
    c6 = "ds.useful_syntax()"

    nb['cells'] = [
        nbf.v4.new_markdown_cell(h1),
        nbf.v4.new_code_cell(c1, metadata=code_meta),
        nbf.v4.new_markdown_cell(h2),
        nbf.v4.new_code_cell(c2, metadata=code_meta),
        nbf.v4.new_code_cell(c3, metadata=code_meta),
        nbf.v4.new_markdown_cell(h3),
        nbf.v4.new_code_cell(c4, metadata=code_meta),
        nbf.v4.new_markdown_cell(h4),
        nbf.v4.new_code_cell(c5, metadata=code_meta ),
        nbf.v4.new_markdown_cell(h5),
        nbf.v4.new_code_cell(c6, metadata=code_meta)
        ]

    with open(f"..//lps_data//datasets//{i['source']}//datasets//{i['table'].lower()}.ipynb", 'w', encoding='utf-8') as f:
        nbf.write(nb, f)

    print(f"""Created new NB for {i["table"]}.""")
    return True

In [5]:
df = md.prep_dsvs_for_gb_pages()

In [64]:
source = "UKREACH"

In [65]:
# creates new ipynb files for missing datasts 
df_source = df[df["source"] == source]
# df_source["table"] = df_source["table"].apply(lambda x: x.lower())

for root, dirnames, filenames in os.walk(f"..//lps_data//datasets//{source.lower()}//datasets"):
    existing_datasets = [i.replace(".ipynb", "") for i in filenames if ".ipynb" in i]
    

df_source["exists"] = df_source["table"].apply(lambda x: x.lower() in existing_datasets)
df_no_nb = df_source[df_source["exists"] == False].reset_index(drop=True)
df_no_nb = df_no_nb[df_no_nb["num_columns"] != ""]

In [66]:
df_no_nb

,source,source_table,version_num,table,version_date,table_name,short_desc,long_desc,collection_start,collection_end,topic_tags,source_name,research_grouping,num_participants,num_rows,num_columns,Owner,geographic_coverage_Nations,geographic_coverage_Regions,exists
0,UKREACH,UKREACH_questionnaire3,1,questionnaire3,20251201.0,UK-REACH Questionnaire 3,"Third questionnaire, updating data.",This questionnaire collects information on eth...,10/2021,12/2021,"Ethnicity,job,covid,family,cultural identity,h...",United Kingdom Research study into Ethnicity A...,"University of Leicester, Department of Respira...",6496.0,6496.0,622.0,University of Leicester,"England, Northern Ireland, Scotland, Wales",Nationwide,False
1,UKREACH,UKREACH_questionnaire1,1,questionnaire1,20251201.0,UK-REACH Questionnaire 1,"Baseline – information on demographics, health...",This baseline questionnaire includes demograph...,12/2020,03/2021,"Ethnicity,job,covid,family,cultural identity,h...",United Kingdom Research study into Ethnicity A...,"University of Leicester, Department of Respira...",15012.0,15015.0,767.0,University of Leicester,"England, Northern Ireland, Scotland, Wales",Nationwide,False
2,UKREACH,UKREACH_questionnaire2,1,questionnaire2,20251201.0,UK-REACH Questionnaire 2,Second questionnaire updating the baseline data.,This questionnaire captures updates on ethnici...,04/2021,06/2021,"Ethnicity,job,covid,family,cultural identity,h...",United Kingdom Research study into Ethnicity A...,"University of Leicester, Department of Respira...",5597.0,5597.0,651.0,University of Leicester,"England, Northern Ireland, Scotland, Wales",Nationwide,False
3,UKREACH,UKREACH_questionnaire6,1,questionnaire6,20251201.0,UK-REACH Questionnaire 6,Sixth questionnaire updating on prior question...,This questionnaire includes ethnicity and cult...,10/2024,04/2025,"Ethnicity,job,long covid,family,harassment,dis...",United Kingdom Research study into Ethnicity A...,"University of Leicester, Department of Respira...",7580.0,7580.0,380.0,University of Leicester,"England, Northern Ireland, Scotland, Wales",Nationwide,False
4,UKREACH,UKREACH_questionnaire4,1,questionnaire4,20251201.0,UK-REACH Questionnaire 4,Fourth questionnaire updating data and adding ...,This questionnaire includes data on ethnicity ...,07/2022,10/2022,"Ethnicity,job,covid,long covid,family,cultural...",United Kingdom Research study into Ethnicity A...,"University of Leicester, Department of Respira...",4224.0,4224.0,646.0,University of Leicester,"England, Northern Ireland, Scotland, Wales",Nationwide,False
5,UKREACH,UKREACH_questionnaire5,1,questionnaire5,20251201.0,UK-REACH Questionnaire 5,Fifth questionnaire updating on prior question...,This questionnaire contains measures of ethnic...,10/2023,01/2024,"Ethnicity,job,covid,long covid,family,cultural...",United Kingdom Research study into Ethnicity A...,"University of Leicester, Department of Respira...",4114.0,4114.0,515.0,University of Leicester,"England, Northern Ireland, Scotland, Wales",Nationwide,False

In [67]:
if len(df_no_nb) > 0:
    df_no_nb["new_ds_page"] = df_no_nb.apply(lambda i: new_lps_ds_nb(i), axis=1)
else:
    print(f"No new datasets to create NBs for {source}.")

Creating new NB for questionnaire3
Created new NB for questionnaire3.
Creating new NB for questionnaire1
Created new NB for questionnaire1.
Creating new NB for questionnaire2
Created new NB for questionnaire2.
Creating new NB for questionnaire6
Created new NB for questionnaire6.
Creating new NB for questionnaire4
Created new NB for questionnaire4.
Creating new NB for questionnaire5
Created new NB for questionnaire5.

In [68]:
files = []
for root, dirnames, filenames in os.walk(f"..//lps_data//datasets//{source.lower()}//datasets"):
    for file in filenames:
        abspath = os.path.abspath(os.path.join(root, file))
        files.append(abspath)

for i in tqdm.tqdm([i for i in files if ".ipynb" in i]): 
    print(f"re-running NB {i}...")
    filename = i
    with open(filename) as ff:
        nb_in = nbf.read(ff, nbf.NO_CONVERT)

    ep = ExecutePreprocessor(timeout=600, kernel_name='python3')
    nb_out = ep.preprocess(nb_in)
    nbf.write(nb_out[0], filename)
    print(f"Completed re-run of NB {i}!")

  0%|          | 0/7 [00:00<?, ?it/s]

re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\questionnaire1.ipynb...

 14%|█▍        | 1/7 [00:25<02:35, 25.93s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\questionnaire1.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\questionnaire2.ipynb...

 29%|██▊       | 2/7 [00:41<01:40, 20.09s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\questionnaire2.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\questionnaire3.ipynb...

 43%|████▎     | 3/7 [00:57<01:12, 18.13s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\questionnaire3.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\questionnaire4.ipynb...

 57%|█████▋    | 4/7 [01:12<00:50, 16.69s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\questionnaire4.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\questionnaire5.ipynb...

 71%|███████▏  | 5/7 [01:26<00:31, 15.92s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\questionnaire5.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\questionnaire6.ipynb...

 86%|████████▌ | 6/7 [01:42<00:16, 16.01s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\questionnaire6.ipynb!
re-running NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\ukreach_datasets.ipynb...

100%|██████████| 7/7 [01:53<00:00, 16.16s/it]

Completed re-run of NB c:\Users\sn9395\GitHub\Guidebook\ukllc_book\docs\lps_data\datasets\ukreach\datasets\ukreach_datasets.ipynb!